# Changes here will be overwritten by Copier
_commit: v0.4.0
_src_path: git@github.com:finitelabs/control4-driver-template.git
project_name: control4-finite-labs-essentials
project_description: Finite Labs Essentials - a collection of independent Control4 drivers
github_org: finitelabs
distributions: drivercentral oss
readme_driver_slug: root
readme_build: oss
primary_color: "#109EFF"
vendor_modules: json deferred drivers-common-public xml