# Changes here will be overwritten by Copier
_commit: 97ff8d0e4a26add83621232c73989a9fe12e2f63
_src_path: git@github.com:finitelabs/control4-driver-template.git
project_name: control4-finite-labs-essentials
project_description: Finite Labs Essentials drivers for Control4
github_org: finitelabs
distributions: drivercentral oss
has_github_updater: true
has_tests: true
readme_driver_slug: light_relay
readme_build: oss
